[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:server_bside]
command=node dist/main.js
directory=/repo/apps/server_bside
environment=PORT="50054",NODE_ENV="production"
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:server_cside]
command=node dist/main.js
directory=/repo/apps/server_cside
environment=NODE_ENV="production"
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:web_admin]
command=/usr/local/bin/serve -s dist -l tcp://0.0.0.0:60061
directory=/repo/apps/web_admin
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:web_platform_builder]
command=node /repo/docker/combined-static.mjs
directory=/repo
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
